=encoding utf8

=head1 NAME

Marquee::Plugin::EPHelperExample - EPヘルパーの定義例

=head1 SYNOPSIS

    $app->plugin('EPHelperExample');

テンプレートにて。。

    <%= commify($price) %>
    <%= min(@prices) %>
    <%= max(@prices) %>
    <%= replace($string, '::', '/') %>
    <%= replace($string, qr/\s/, '') %>

=head1 DESCRIPTION

これはEPテンプレート関数を追加するサンプルプラグインです。

=head1 FUNCTIONS

下記のテンプレート関数が自動的に利用可能です。

=head2 commify

指定の数値をカンマ付きの書式にします。

    <%= commify(123456789) %> <!-- 123,456,789 -->

=head2 min

数値の配列から最小の値を見つけます。

    <%= min(1, 2, 3) %> <!-- 1 -->

=head2 max

数値の配列から最大の値を見つけます。

    <%= max(1, 2, 3) %> <!-- 3 -->

=head2 replace

指定の文字列中の指定の文字列かパターンを置換します。

    <%= replace('foo::bar', '::', '/') %> <!-- foo/bar -->
    <%= replace('foo::::bar', qr{:+}, '/') %> <!-- foo/bar -->

=head1 INSTANCE METHODS

L<Marquee::Plugin::EPHelperExample>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 C<register>

プラグインを登録します。

    $self->register($app);

=head1 SEE ALSO

L<Marquee::SSIHandler::EP>, L<Marquee>, L<Mojolicious>

=cut
