=encoding utf8

=head1 NAME

Mojolicious::Command::marquee - marquee command

=head1 SYNOPSIS

  use Mojolicious::Command::marquee;

  my $app = Mojolicious::Command::marquee->new;
  $app->run(@ARGV);

=head1 DESCRIPTION

=head1 ATTRIBUTES

=head2 description

=head2 usage

=head1 INSTANCE METHODS

L<Marquee::Command::marquee>は
L<Marquee::Command>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 run

=head1 SEE ALSO

L<marquee>

=cut
