=encoding utf8

__END__

=head1 NAME

Marquee::Plugin::Auth - ベーシック認証

=head1 SYNOPSIS
    
    $self->plugin(Auth => [
        qr{^/admin/} => 'Secret Area' => sub {
            my ($username, $password) = @_;
            return $username eq 'user' &&  $password eq 'pass';
        },
        qr{^/admin/} => 'Secret Area2' => sub {
            my ($username, $password) = @_;
            return $username eq 'user' &&  $password eq 'pass';
        },
    ]);

=head1 DESCRIPTION

このプラグインはディスパッチャ全体をラップすることで、指定のパスにベーシック認証をかけます。

=head1 ATTRIBUTES

L<Marquee::Plugin::Auth>は
L<Marquee::Plugin>の全ての属性を継承し、下記を追加で実装します。

=head2 realm

レスポンスヘッダに出現するrealmのデフォルト値を指定します。それぞれの認証設定はこれをオーバーライドすることができます。

=head1 INSTANCE METHODS

L<Marquee::Plugin::Auth>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 $instance->register($app, $path_entries)

パスエントリーを指定して、プラグインを登録します。$path_entriesは、正規表現とrealmとコールバックの組み合わせ
が連続するリストでなければなりません。なお、realmはオプションです。

=head2 EXAMPLE

You can port apache htpasswd entries as follows.

    my $htpasswd = {
        user1 => 'znq.opIaiH.zs',
        user2 => 'dF45lPM2wMCDA',
    };
    
    $self->plugin(Auth => [
        qr{^/admin/} => 'Secret Area' => sub {
            my ($username, $password) = @_;
            if (my $expect = $htpasswd->{$username}) {
                return crypt($password, $expect) eq $expect;
            }
        },
    ]);

=head1 SEE ALSO

L<Marquee>, L<Mojolicious>

=cut
