=encoding utf8

=head1 NAME

Marquee::Plugin::AutoIndex - オートインデックス

=head1 SYNOPSIS

    $app->plugin('AutoIndex');

On your browser following forms of URL are available.

    http://localhost:3000/path/to/directory/
    http://localhost:3000/path/to/directory/?mode=tree

=head1 DESCRIPTION

このプラグインはオートインデックスを可能とします。アプリのdefault_file属性が未定義か、指定のファイルが存在しないとき、
ディレクトリへのアクセスに対してオートインデックスが返されます。

=head1 ATTRIBUTES

=head2 max_per_dir

ディレクトリ内で表示可能なファイル数の上限を指定します。

=head2 tree_depth

ディレクトリの再帰処理の深度の上限を指定します。

=head1 METHODS

=head2 $instance->register($app, $hash_ref)

=head2 $instance->serve_index

Serves auto directory index.

=head2 $instance->serve_tree

Serves auto directory tree.

=head1 SEE ALSO

L<Marquee>, L<Mojolicious>

=cut
