=encoding utf8

=head1 NAME

Marquee::Plugin::AutoIndex - オートインデックス

=head1 SYNOPSIS

    $app->plugin('AutoIndex');

ブラウザにて、下記のURL書式が利用可能になります。

    http://localhost:3000/path/to/directory/
    http://localhost:3000/path/to/directory/?mode=tree

=head1 DESCRIPTION

このプラグインはオートインデックスを可能とします。アプリのdefault_file属性が未定義か、指定のファイルが存在しないとき、
ディレクトリへのアクセスに対してオートインデックスが返されます。

=head1 ATTRIBUTES

L<Marquee::Plugin::AutoIndex>は
L<Marquee::Plugin>の全ての属性を継承し、下記を追加で実装します。

=head2 C<max_per_dir>

ディレクトリ内で表示可能なファイル数の上限を指定します。デフォルトは50です。

    $plugin->max_per_dir(100);
    my $num = $plugin->max_per_dir;

=head2 C<tree_depth>

ディレクトリの再帰処理の深度の上限を指定します。デフォルトは4です。

    $plugin->tree_depth(2);
    my $num = $plugin->tree_depth;

=head1 INSTANCE METHODS

L<Marquee::Plugin::AutoIndex>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 C<register>

プラグインを登録します。

    $self->register($app);

=head2 C<serve_index>

自動生成されたディレクトリインデックスを出力します。

    $plugin->serve_index($path);

=head2 C<serve_tree>

自動生成されたディレクトリツリーを出力します。

    $plugin->serve_tree($path);

=head1 SEE ALSO

L<Marquee>, L<Mojolicious>

=cut
