=encoding utf8

=head1 NAME

Marquee::Plugin::AutoIndex - オートインデックス

=head1 SYNOPSIS

    $app->plugin('AutoIndex');

On your browser following forms of URL are available.

    http://localhost:3000/path/to/directory/
    http://localhost:3000/path/to/directory/?mode=tree

=head1 DESCRIPTION

このプラグインはオートインデックスを可能とします。アプリのdefault_file属性が未定義か、指定のファイルが存在しないとき、
ディレクトリへのアクセスに対してオートインデックスが返されます。

=head1 ATTRIBUTES

L<Marquee::Plugin::AutoIndex>は
L<Marquee::Plugin>の全ての属性を継承し、下記を追加で実装します。

=head2 max_per_dir

ディレクトリ内で表示可能なファイル数の上限を指定します。デフォルトは50です。

    $plugin->max_per_dir(100);
    my $num = $plugin->max_per_dir;

=head2 tree_depth

ディレクトリの再帰処理の深度の上限を指定します。デフォルトは4です。

    $plugin->tree_depth(2);
    my $num = $plugin->tree_depth;

=head1 INSTANCE METHODS

L<Marquee::Plugin::AutoIndex>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 $instance->register($app, $hash_ref)

プラグインを登録します。

    $self->register($app);

=head2 $instance->serve_index

Serves auto directory index.

    $plugin->serve_index($path);

=head2 $instance->serve_tree

Serves auto directory tree.

    $plugin->serve_tree($path);

=head1 SEE ALSO

L<Marquee>, L<Mojolicious>

=cut
