=encoding utf8

=head1 NAME

Marquee::Plugin::EPHelperExample - EPヘルパーの定義例

=head1 SYNOPSIS

    <%= commify($price) %>
    <%= min(@prices) %>
    <%= max(@prices) %>
    <%= replace($string, '::', '/') %>
    <%= replace($string, qr/\s/, '') %>

=head1 DESCRIPTION

これはEPテンプレート関数を追加するサンプルプラグインです。

=head1 INSTANCE METHODS

L<Marquee::Plugin::EPHelperExample>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 $instance->register($app, $routes)

=head1 SEE ALSO

L<Marquee::SSIHandler::EP>, L<Marquee>, L<Mojolicious>

=cut
