=encoding utf8

=head1 NAME

Marquee::Plugin::PODRenderer - PODビュワープラグイン

=head1 SYNOPSIS

    $app->plugin('PODViewer');
    
    # on brower the following url for example will be available.
    #
    # http://localhost:3000/perldoc/LWP

=head1 DESCRIPTION

このプラグインは、PODビュワーサーバーです。

=head1 ATTRIBUTES

L<Marquee::Plugin::PODViewer>は
L<Marquee::Plugin>の全ての属性を継承し、下記を追加で実装します。

=head2 no_see_also

関連するモジュールの自動検出を無効にします。

=head2 paths

モジュールを探すパスです。

=head1 INSTANCE METHODS

L<Marquee::Plugin::PODViewer>は
L<Marquee::Plugin>の全てのインスタンスメソッドを継承し、下記を追加で実装します。

=head2 $instance->register($app)

=head2 $instance->serve_index()

=head2 $instance->serve_pod($html)

=head2 $instance->serve_pod_by_name($module_name)

=head1 SEE ALSO

L<Marquee>, L<Mojolicious>

=cut
