=encoding utf8

=head1 NAME

Marquee::SSIHandler::EPL - EPLテンプレートハンドラー

=head1 SYNOPSIS

    my $epl = Marquee::SSIHandler::EPL->new;
    $epl->render('/path/to/template.html.ep');

=head1 DESCRIPTION

EPLハンドラー。

=head1 ATTRIBUTES

L<Marquee::SSIHandler::EPL>は
L<Marquee::SSIHandler>の全ての属性を継承し、下記の属性を追加で実装します。

=head2 template_cache

    my $cache = $epl->template_cache;

=head1 INSTANCE METHODS

L<Marquee::SSIHandler::EPL>は
L<Marquee::SSIHandler>の全てのメソッドを継承し、下記を追加で実装します。

=head2 $instance->cache($path, $mt)

キャッシュの保存/読み出しを行います。

    $epl->cache('/path/to/template.html.ep', $mt);
    my $mt = $epl->cache('/path/to/template.html.ep');

=head2 $instance->render($path)

指定のテンプレートをレンダリングし、結果を返します。レンダリングに失敗した場合、L<Mojo::Exception>を伴って
dieします。

=head1 SEE ALSO

L<Marquee::SSIHandler>, L<Marquee>, L<Mojolicious>

=cut
