=head1 NAME

Marquee::SSIHandler::EPL - EPL template handler

=head1 SYNOPSIS

    my $epl = Marquee::SSIHandler::EPL->new;
    $epl->render('/path/to/template.html.ep');

=head1 DESCRIPTION

EPL handler.

=head1 ATTRIBUTES

L<Marquee::SSIHandler::EPL> inherits all attributes from
L<Marquee::SSIHandler> and implements the following new ones.

=head2 template_cache

    my $cache = $epl->template_cache;

=head1 METHODS

L<Marquee::SSIHandler::EPL> inherits all methods from
L<Marquee::SSIHandler> and implements the following new ones.

=head2 $instance->cache($path, $mt)

Get or set cache.

    $epl->cache('/path/to/template.html.ep', $mt);
    my $mt = $epl->cache('/path/to/template.html.ep');

=head2 $instance->render($path)

Renders given template and returns the result. If rendering fails, die with
L<Mojo::Exception>.

=head1 SEE ALSO

L<Marquee::SSIHandler>, L<Marquee>, L<Mojolicious>

=cut
