=encoding utf8

=head1 NAME

Marquee::SSIHandler - SSIハンドラーベースクラス

=head1 SYNOPSIS

    package Marquee::SSIHandler::EPL;
    use Mojo::Base 'Marquee::SSIHandler';
    
    sub render {
        my ($self, $path) = @_;
        
        ...;
        
        return $out;
    }

=head1 DESCRIPTION

本クラスは、ハンドラークラスに継承されるベースクラスです。サブクラスはC<render>を実装しなければなりません。

=head1 ATTRIBUTES

L<Marquee::SSIHandler>は下記の属性を実装します。

=head2 C<log>

C<Mojo::Log>インスタンスです。デフォルトは、もし存在すればC<$app-E<gt>log>です。

    $handler->log('/path/to/handler.log');
    $path = $handler->log;

=head1 CLASS METHODS

L<Marquee::SSIHandler>は下記のクラスメソッドを実装します。

=head2 C<current_template>

現在のテンプレートを再帰的に検出します。

    my $current_template = Marquee::SSIHandler->current_template;
    my $parent_template = Marquee::SSIHandler->current_template(1);

=head1 INSTANCE METHODS

L<Marquee::SSIHandler>は下記のインスタンスメソッドを実装します。

=head2 C<render>

テンプレートをレンダリングします。サブクラスはこのメソッドをオーバーライドしなければなりません。
    
    sub render {
        my ($self, $path) = @_;
        
        ...;
        
        return $out;
    }

どこかで。。

    $handler->render($path);

=head2 render_traceable($path)

テンプレート名を再帰的にスタックすることで、トレース可能にレンダリングします。

    $handler->render_traceable($path);

=head2 traceable($path, sub {...})

トレース可能にコールバックを実行します。

    $handler->traceable($path, sub {...});

=head1 SEE ALSO

L<Marquee::SSIHandler::EPL>,
L<Marquee::SSIHandler::EP>, L<Marquee>, L<Mojolicious>

=cut
